version: '3'
services:

  # Elasticsearch
  eslogs:
    image: elasticsearch:7.8.0
    container_name: eslogs
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elastic/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  # Kibana. Gotta have a pretty UI, amiright?
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    volumes:
    - ./elastic/kibana.yaml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  # All hail the mighty, mighty LOOOOOOOGSTAAAAAAAAASH:
  logstash:
    image: logstash:7.8.1
    container_name: logstash
    volumes:
    - ./elastic/logging.conf:/usr/share/logstash/pipeline/logstash.conf
    - ./elastic/logstash.yaml:/usr/share/logstash/config/logstash.yml
    ports:
      - 1514:1514/udp
      - 1515:1515
      - 1515:1515/udp
volumes:
  elasticsearch_data:
    driver: local
  api_db_data:
    driver: local
